server:
  port: ${CONFIG_PORT:8080}
spring:
  application: #app discovery  config
    name: Api-Gateway
  cloud:
    config:
      uri: http://${CONFIG_SERVICE:localhost}:${CONFIG_PORT:7761}
  main:
    web-application-type: reactive