server:
  port: ${GATEWAY_PORT:8060}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/banque-realm/protocol/openid-connect/certs
  application: #app discovery  config
    name: Api-Gateway
  main:
    web-application-type: reactive
  cloud:
    config:
      uri: http://${CONFIG_SERVICE:localhost}:${CONFIG_PORT:7761}
    gateway:
      routes:
      - id: Parametrage-Service
        uri: http://${PARAMETRAGE_SERVICE:localhost}:8090/
        predicates:
        - Path=/parametrage/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}
      - id: Demande-Service
        uri: http://${DEMANDE_SERVICE:localhost}:8091/
        predicates:
        - Path=/demande/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}
      - id: Parametrage-Service-NotFound
        uri: forward:/parametrage-service-not-found
        predicates:
        - Path=/parametrage/**
      - id: Demande-Service-NotFound
        uri: forward:/demande-service-not-found
        predicates:
        - Path=/demande/**
      - id: Camunda-Service
        uri: http://${Camunda_SERVICE:localhost}:7001/
        predicates:
        - Path=/camunda/**
      - id: Image-Service
        uri: http://${PARAMETRAGE_SERVICE:localhost}:8090/
        predicates:
        - Path=/images/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            AllowedHeaders:
              - Content-Type


eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:localhost}:${DISCOVERY_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
         include: "*"
