server:
  port: ${CONFIG_PORT:8060}
spring:
  application: #app discovery  config
    name: Api-Gateway
  main:
    web-application-type: reactive
  cloud:
    config:
      uri: http://${CONFIG_SERVICE:localhost}:${CONFIG_PORT:7761}
    gateway:
      routes:
      - id: Parametrage-Service
        uri: http://localhost:8090/
        predicates:
        - Path=/parametrage/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}
      - id: Demande-Service
        uri: http://localhost:8091/
        predicates:
        - Path=/demande/**
        filters:
        - RewritePath=/(?<path>.*), /$\{path}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - Content-Type


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints: 
    web: 
      exposure:
         include: "*"